/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Renderer {
  width: number
  height: number
  constructor(width: number, height: number)
  render(backBuffer: Uint32Array): void
}

export declare class TerminalSetup {
  static enter(): void
  static leave(): void
  static getSize(): Array<number>
}

export interface DevToolsProps {
  children: React.ReactNode
  enabled?: boolean
}
export declare function DevTools(props: DevToolsProps): React.ReactElement
